server:
  servlet:
    context-path: /j2etpapp
  port: 8080

spring:
  application:
    name: J2ETPApp
  profiles:
    active: dev
  # i18n
  messages:
    basename: i18n/common
  # JPA
  jpa:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MariaDB53Dialect
        dialect: org.hibernate.dialect.MariaDB103Dialect
        #current_session_context_class: thread
        #hbm2ddl.auto: validate
        #hbm2ddl.auto: create-drop
        hbm2ddl.auto: update
        #format_sql: false
        show_sql: true
        jdbc:
          time_zone: Europe/Warsaw

  # MONGO
  data:
    mongodb:
      authentication-database: admin
      username: j2etp
      password: j2etp
      database: j2etpapp
      port: 27017
      host: localhost
  # files
  servlet:
    multipart:
      max-file-size: 10MB

###############################################
############# POSTD PROPERTIES ################
###############################################

postd:
  imagesStoragePath: 'storage/images/'
  dateFormat: yyyy-MM-dd
  minPasswordLength: 6
