spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j2etpapp?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: j2etp
    password: j2etp
    driver-class-name: com.mysql.cj.jdbc.Driver